version: '3.7'

services:
  webcrawler:
    image: webcrawler:latest
    build:
      context: .
      cache_from:
        - webcrawler:latest
    container_name: webcrawler
    depends_on:
      - webcrawler-mysql
      - webcrawler-memcached
      - webcrawler-rabbitmq
    env_file:
      - .env
    volumes:
      - ./attachments/scripts/waitforit:/tmp/waitforit
    command: sh -c "
      /tmp/waitforit -timeout 30 -address tcp://webcrawler-mysql:3306 &&
      /tmp/waitforit -timeout 30 -address tcp://webcrawler-memcached:11211 &&
      /tmp/waitforit -timeout 30 -address tcp://webcrawler-rabbitmq:5672 &&
      python -m webcrawler"

  webcrawler-mysql:
    image: mysql:8.0.21
    container_name: webcrawler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: webcrawler
    ports:
      - 3309:3306
    volumes:
      - ./attachments/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    cap_add:
      - SYS_NICE
    command: ['mysqld','--character-set-server=UTF8MB4','--default-authentication-plugin=mysql_native_password', '--performance-schema=off']

  webcrawler-rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: webcrawler-rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./attachments/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./attachments/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    command: bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_federation_management rabbitmq_mqtt rabbitmq_stomp rabbitmq_shovel rabbitmq_shovel_management rabbitmq_peer_discovery_k8s && rabbitmq-server"

  webcrawler-memcached:
    image: memcached:1.6.6-alpine
    container_name: webcrawler-memcached
    ports:
      - 11211:11211
    command: ["memcached", "-m", "1024M", "-c","32768","-I","10M"]

  webcrawler-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webcrawler-phpmyadmin
    environment:
      - PMA_HOST=webcrawler-mysql
      - PMA_USER=root
      - PMA_PASSWORD=123123
    ports:
      - 8996:80
    depends_on:
      - webcrawler-mysql

  webcrawler-main-services:
    image: alpine
    container_name: webcrawler-main-services
    depends_on:
      - webcrawler-mysql
      - webcrawler-phpmyadmin
      - webcrawler-memcached
      - webcrawler-rabbitmq
    command: sh -c "echo start"