version: '3.7'

services:
  webcrawler:
    image: webcrawler:latest
    build:
      context: .
      cache_from:
        - webcrawler:latest
    container_name: webcrawler
    depends_on:
      - webcrawler-mysql
    env_file:
      - .env
    volumes:
      - ./attachments/scripts/waitforit:/tmp/waitforit
    command: sh -c "
      /tmp/waitforit -timeout 30 -address tcp://webcrawler-mysql:3306 &&
      /tmp/waitforit -timeout 30 -address tcp://webcrawler-memcached:11211 &&
      python3 -m webcrawler"

  webcrawler-mysql:
    image: mysql:8.0.21
    container_name: webcrawler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: webcrawler
    ports:
      - 3309:3306
#    volumes:
#      - ./attachments/mysql/dump.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: ['mysqld','--character-set-server=UTF8MB4','--default-authentication-plugin=mysql_native_password', '--performance-schema=off']

  webcrawler-memcached:
    image: memcached:1.6.6-alpine
    container_name: webcrawler-memcached
    ports:
      - 11211:11211
    command: ["memcached", "-m", "1024M", "-c","32768","-I","10M"]

  webcrawler-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webcrawler-phpmyadmin
    environment:
      - PMA_HOST=webcrawler-mysql
      - PMA_USER=root
      - PMA_PASSWORD=123123
    ports:
      - 8996:80
    depends_on:
      - webcrawler-mysql

  webcrawler-main-services:
    image: alpine
    container_name: webcrawler-main-services
    depends_on:
      - webcrawler-mysql
      - webcrawler-phpmyadmin
      - webcrawler-memcached
    command: sh -c "echo start"